AWSTemplateFormatVersion: 2010-09-09
Description: Lex Interceptor
Parameters:
  AllowedLanguages:
    Default: zh-TW,en
    Type: String
  BotAlas:
    Default: $LATEST
    Type: String
  BotName:
    Default: InfoDay_InfoDayBot
    Type: String
  FacebookPageToken:
    Description: Facebook Page Token
    NoEcho: true
    Type: String
  FacebookVerifyToken:
    Default: testing
    Description: Facebook Verify Token
    Type: String
  GoogleApiKey:
    NoEcho: true
    Type: String
  SourceBucket:
    Default: howwhofeelinvideopackage
    Description: Bucket Lambda deployment packages
    Type: String
  SpeechRecognizeLanguage:
    Default: yue-Hant-HK
    Type: String
Resources:
  AttachmentBucket:
    Properties:
      AccessControl: Private
    Type: AWS::S3::Bucket
  DecodeQrcode:
    Properties:
      CodeUri:
        Bucket:
          Ref: SourceBucket
        Key: QrcodeDecoderLambda-1.0-SNAPSHOT-all.jar
      Description: Decode Qrcode by sending in Url string.
      Handler: com.cloudlab.healthAi.qrcode.QrcodeHandler::handleRequest
      MemorySize: 1024
      Policies:
      - AWSXrayWriteOnlyAccess
      - AmazonRekognitionFullAccess
      - AWSLambdaExecute
      - AWSLambdaBasicExecutionRole
      Runtime: java8
      Timeout: 60
      Tracing: Active
    Type: AWS::Serverless::Function
  FacebookLexInterceptor:
    Properties:
      CodeUri:
        Bucket:
          Ref: SourceBucket
        Key: LexInterceptor_latest.zip
      Description: Interceptor Facebook Request
      Environment:
        Variables:
          ALLOWED_LANGUAGES:
            Ref: AllowedLanguages
          ATTACHMENT_BUCKET:
            Ref: AttachmentBucket
          BOT_ALIAS:
            Ref: BotAlas
          BOT_NAME:
            Ref: BotName
          GOOGLE_API_KEY:
            Ref: GoogleApiKey
          IMAGE_TABLE:
            Ref: ImageTable
          PAGE_TOKEN:
            Ref: FacebookPageToken
          QRCODE_FUNCTION:
            Ref: DecodeQrcode
          SESSION_TABLE_NAME:
            Ref: SessionTable
          SPEECH_RECOGNIZE_LANGUAGE:
            Ref: SpeechRecognizeLanguage
          VERIFY_TOKEN:
            Ref: FacebookVerifyToken
          VOICE_BUCKET:
            Ref: VoiceBucket
          VOICE_SITE_URL:
            Fn::GetAtt:
            - VoiceBucket
            - WebsiteURL
      Events:
        GetMessage:
          Properties:
            Method: get
            Path: /
          Type: Api
        PostMessage:
          Properties:
            Method: post
            Path: /
          Type: Api
      Handler: facebookInterceptor.handler
      MemorySize: 512
      Policies:
      - AWSLambdaExecute
      - AWSXrayWriteOnlyAccess
      - AmazonRekognitionFullAccess
      - AmazonDynamoDBFullAccess
      - Statement:
        - Action:
          - lambda:InvokeFunction
          - lex:PostText
          - polly:DescribeVoices
          - polly:SynthesizeSpeech
          Effect: Allow
          Resource: '*'
        - Action:
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
          Effect: Allow
          Resource:
          - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${SessionTable}
        Version: '2012-10-17'
      Runtime: nodejs6.10
      Timeout: 60
      Tracing: Active
    Type: AWS::Serverless::Function
  ImageTable:
    Type: AWS::Serverless::SimpleTable
  SessionTable:
    Type: AWS::Serverless::SimpleTable
  VoiceBucket:
    DeletionPolicy: Retain
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        ErrorDocument: error.html
        IndexDocument: index.html
    Type: AWS::S3::Bucket
  VoiceBucketPolicy:
    Properties:
      Bucket:
        Ref: VoiceBucket
      PolicyDocument:
        Id: VoiceBucketPolicy
        Statement:
        - Action: s3:GetObject
          Effect: Allow
          Principal: '*'
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - Ref: VoiceBucket
              - /*
          Sid: PublicReadForGetBucketObjects
        Version: 2012-10-17
    Type: AWS::S3::BucketPolicy
Transform: AWS::Serverless-2016-10-31
