AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Lex Interceptor
Parameters:
  SourceBucket:
    Type: String
    Default: howwhofeelinvideopackage
    Description: Bucket Lambda deployment packages
  FacebookVerifyToken:
    Type: String
    Default: testing
    Description: Facebook Verify Token
  FacebookPageToken:
    Type: String
    Description: Facebook Page Token
    NoEcho: true
  BotAlas:
    Type: String
    Default: $LATEST
  BotName:
    Type: String
    Default: InfoDay_InfoDayBot
  GoogleApiKey:
    Type: String
    NoEcho: true
  AllowedLanguages:
    Type: String
    Default: zh-TW,zh-HK,en
  SpeechRecognizeLanguage:
    Type: String
    Default: yue-Hant-HK
  SynthesizeSpeechLanguageHints:
    Type: String
    Default: '{"zh":"zh-HK"}'
Resources:
  DecodeQrcode:
    Type: AWS::Serverless::Function
    Properties:
      Description: Decode Qrcode by sending in Url string.
      Handler: com.cloudlab.healthAi.qrcode.QrcodeHandler::handleRequest
      Runtime: java8
      MemorySize: 1024
      Timeout: 60
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - AmazonRekognitionFullAccess
        - AWSLambdaExecute
        - AWSLambdaBasicExecutionRole
      CodeUri:
        Bucket: !Ref SourceBucket
        Key: QrcodeDecoderLambda-1.0-SNAPSHOT-all.jar

  FacebookLexInterceptor:
    Type: AWS::Serverless::Function
    Properties:
      Handler: facebookInterceptor.handler
      Runtime: nodejs6.10
      CodeUri:
        Bucket: !Ref SourceBucket
        Key: LexInterceptor_latest.zip
      Description: Interceptor Facebook Request
      MemorySize: 512
      Timeout: 60
      Tracing: Active
      Policies:
        - AWSLambdaExecute # Managed Policy
        - AWSXrayWriteOnlyAccess
        - AmazonRekognitionFullAccess
        - AmazonDynamoDBFullAccess
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
              - lambda:InvokeFunction
              - lex:PostText
              - polly:DescribeVoices
              - polly:SynthesizeSpeech
              Resource: "*"
            - Effect: Allow
              Action:
              - dynamodb:Scan
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
              Resource:
              - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${SessionTable}
      Environment:
        Variables:
          QRCODE_FUNCTION: !Ref DecodeQrcode
          PAGE_TOKEN: !Ref FacebookPageToken
          VERIFY_TOKEN: !Ref FacebookVerifyToken
          BOT_ALIAS: !Ref BotAlas
          BOT_NAME: !Ref BotName
          GOOGLE_API_KEY: !Ref GoogleApiKey
          ATTACHMENT_BUCKET: !Ref AttachmentBucket
          VOICE_BUCKET: !Ref VoiceBucket
          VOICE_SITE_URL:  !GetAtt VoiceBucket.WebsiteURL
          SESSION_TABLE_NAME : !Ref SessionTable
          IMAGE_TABLE: !Ref ImageTable
          TRANSLATION_CACHE_TABLE: !Ref TranslationCacheTable
          ALLOWED_LANGUAGES: !Ref AllowedLanguages
          SPEECH_RECOGNIZE_LANGUAGE: !Ref SpeechRecognizeLanguage
          SYNTHESIZE_SPEECH_LANGUAGE_HINTS: !Ref SynthesizeSpeechLanguageHints
      Events:
        PostMessage:
          Type: Api
          Properties:
            Path: /
            Method: post
        GetMessage:
          Type: Api
          Properties:
            Path: /
            Method: get

  AttachmentBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private

  VoiceBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain
  VoiceBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Id: VoiceBucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref VoiceBucket
                - /*
      Bucket: !Ref VoiceBucket

  SessionTable:
    Type: AWS::Serverless::SimpleTable

  ImageTable:
    Type: AWS::Serverless::SimpleTable

  TranslationCacheTable:
    Type: AWS::Serverless::SimpleTable